version: '3.4'

services:
  dockervscode:
    image: dockervscode
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:latest
    volumes:
      - ./redis-vol:/data
    ports:
      - 6379:6379
